### PR TITLE
Issue 16 fix url bug

### LINKED ISSUE #16: Translating lines with URL gives error
Hi there 👋 sir Tomeriko,

First of all — wow, I love this package. It's exactly what I needed to handle translation workflows in R, and I really appreciate the clean API and flexibility you've built into it 🙌

While using `google_translate()` to process some script comments, I ran into the following error:

```r
google_translate("# Web Page: http://www.hhs.nl", target_language = "en")
#> Error in open.connection(x, "rb") : cannot open the connection
```

Is this something you've seen before? Happy to provide more info if needed — and again, thanks for such a great tool. It's been a pleasure to work with it so far.

All the best,

aslamht

### PR DESCRIPTION
**Pull request by aslamht**
## Summary
This PR adds error handling for (malformed) URLs in the google_translate function.

## Fixes
Fixes #16 

## Notes
This PR applies the fix for malformed URL placeholders to the main `google_translate()` function.

Other variants of `google_translate` still need this update, but I currently don't have time to apply it across all of them. I recommend tracking this as a follow-up task.

### CODE REVIEW

File: R/google_translate.R [hunk 1]
```diff
@@ -17,47 +20,59 @@
...
   }
 
+  ## Check if input is a vector of strings
   is_vector <- is.vector(text) && length(text) > 1
 
-  formatted_text <- urltools::url_encode(text)
+  if (is_vector) {
+    ## Translate each sentence in the vector
+    translations <- purrr::map_chr(text, function(t) {
+      replaced <- replace_urls_with_placeholders(t)
```
Comment (Tomeriko96) [inline R/google_translate.R:39]: Have you checked what happens when the text does not contain a url link?

File: helperfunctions/url_helpers.R [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+    placeholder <- paste0("__URL", i, "__")
+
+    ## Replace exact placeholder
+    restored_text <- stringr::str_replace(restored_text, stringr::fixed(placeholder), urls[i])
+
+    ## Also try replacing lowercase version in case translation changed casing
+    restored_text <- stringr::str_replace(restored_text, stringr::fixed(stringr::str_to_lower(placeholder)), urls[i])
+  }
+  restored_text
+}
```
Comment (Tomeriko96) [inline helperfunctions/url_helpers.R:32]: Please add roxygen to the functions. No need to add export tag in this case

**Review by Tomeriko96 — CHANGES_REQUESTED** [review]
- Please fix the errors in the automated checks
- the `helperfunctions` directory should not be used for this url_helpers.R --> should go to the R/ directory instead

**Comment by Tomeriko96** [comment]
Hi @aslamht 

Thank you for your PR. Please fix the issues and look into the code review comments for me to merge.

Also provide example cases with and without url links in the text.

File: R/google_translate.R (hunk 1 above)
Comment (aslamht) [reply R/google_translate.R:39]: Thank you for the comment. Translating text without url link works as expected.

File: helperfunctions/url_helpers.R (hunk 2 above)
Comment (aslamht) [reply helperfunctions/url_helpers.R]: Thanks for the change request. I have added the roxygen

**Review by Tomeriko96 — APPROVED** [review]
Looks great, thanks!
